/**
 * Shared SEO copy for eagleeyechauffeur.com (NYC chauffeur / black car).
 * Titles & descriptions are primary signals; keywords supplement other systems.
 */
export const siteKeywords: string[] = [
  'NYC chauffeur',
  'New York chauffeur service',
  'chauffeur service NYC',
  'Manhattan black car service',
  'black car service NYC',
  'NYC black car service',
  'luxury car service NYC',
  'executive car service New York',
  'private driver NYC',
  'chauffeur service Manhattan',
  'Brooklyn chauffeur',
  'Brooklyn black car service',
  'Queens car service',
  'Queens black car service',
  'Bronx car service',
  'Staten Island car service',
  'Westchester car service',
  'Long Island chauffeur',
  'New Jersey car service NYC',
  'NYC airport car service',
  'airport transfer NYC',
  'JFK car service',
  'JFK airport car service',
  'JFK airport transfer',
  'JFK black car',
  'LaGuardia car service',
  'LGA car service',
  'LGA airport car service',
  'LGA airport transfer',
  'Newark airport car service',
  'EWR airport car service',
  'EWR airport transfer',
  'EWR car service',
  'Westchester airport HPN car service',
  'corporate car service NYC',
  'executive transportation NYC',
  'corporate chauffeur NYC',
  'roadshow chauffeur New York',
  'hourly chauffeur NYC',
  'point to point car service NYC',
  'wedding car service NYC',
  'special event chauffeur New York',
  'premium sedan SUV NYC',
  'Eagle Eye Chauffeur',
];

export const defaultSiteDescription =
  'NYC luxury chauffeur and black car service: Manhattan & boroughs, JFK LGA EWR HPN airport transfers, hourly chauffeur, corporate travel, and point-to-point rides. Eagle Eye Chauffeur.';
